import { DEFAULT_COMMISSION_RULES, DEFAULT_RANKS, SCHEME_KINDS, normalizeConfig } from './simulation.js';

const customRecruitment = {
  id: 'custom-recruitment',
  name: 'Recruitment pyramid sandbox',
  kind: SCHEME_KINDS.RECRUITMENT,
  mode: 'interactive',
  description: 'Explore how fees, purchases, upline commissions, ranks, churn, and a finite recruitment pool interact.',
  seed: 42,
  maxPeriods: 48,
  initialParticipants: 1,
  addressablePopulation: 2_000_000,
  initialReserve: 2_500,
  growth: {
    recruitsPerParticipant: 2.5,
    recruitmentDecay: 0.965,
    churnRate: 0.08,
    churnSensitivity: 0.32,
    marketFriction: 1.35,
  },
  recruitment: {
    joinFee: 500,
    recurringPurchase: 100,
    retailSalesPerParticipant: 20,
    retailMargin: 0.35,
    refundRate: 0.12,
    productCostRate: 0.25,
    operatorSkimRate: 0.12,
    commissionRules: DEFAULT_COMMISSION_RULES,
    ranks: DEFAULT_RANKS,
  },
};

const customInvestment = {
  id: 'custom-investment',
  name: 'Investment Ponzi sandbox',
  kind: SCHEME_KINDS.INVESTMENT,
  mode: 'interactive',
  description: 'Model deposits, fabricated returns, withdrawal pressure, operator diversion, and confidence shocks.',
  seed: 84,
  maxPeriods: 60,
  initialParticipants: 10,
  addressablePopulation: 1_000_000,
  initialReserve: 25_000,
  initialTotalInflow: 50_000,
  initialClaimedAccountValue: 50_000,
  growth: {
    recruitsPerParticipant: 0.45,
    recruitmentDecay: 0.975,
    churnRate: 0.04,
    churnSensitivity: 0.4,
    marketFriction: 1.3,
  },
  investment: {
    depositPerRecruit: 5_000,
    recurringDeposit: 0,
    promisedReturnRate: 0.12,
    withdrawalRate: 0.04,
    genuineRevenueRate: 0,
    operatorSkimRate: 0.08,
  },
};

export const scenarios = [
  customRecruitment,
  customInvestment,
  {
    id: 'charles-ponzi',
    name: 'Charles Ponzi, 1920',
    kind: SCHEME_KINDS.INVESTMENT,
    mode: 'historical',
    immutable: true,
    historicalCaseId: 'charles-ponzi',
    description: 'Eight-month replay calibrated to the documented $15 million intake and 50% return promise.',
    seed: 1920,
    maxPeriods: 8,
    initialParticipants: 800,
    addressablePopulation: 100_000,
    initialReserve: 100_000,
    initialTotalInflow: 200_000,
    initialClaimedAccountValue: 200_000,
    growth: {
      recruitsPerParticipant: 0.78,
      recruitmentDecay: 0.97,
      churnRate: 0.05,
      churnSensitivity: 0.28,
      marketFriction: 1.25,
    },
    investment: {
      depositPerRecruit: 800,
      recurringDeposit: 0,
      promisedReturnRate: 0.145,
      withdrawalRate: 0.06,
      genuineRevenueRate: 0,
      operatorSkimRate: 0.08,
    },
    shocks: [
      { period: 7, label: 'Press scrutiny raises doubts and withdrawal requests.', recruitmentMultiplier: 0.38, withdrawalMultiplier: 4, churnAdd: 0.12 },
      { period: 8, label: 'The public investigation and audit end the operation.', recruitmentMultiplier: 0, withdrawalMultiplier: 8, churnAdd: 0.4, freeze: true },
    ],
    benchmarks: [
      { id: 'ponzi-duration', label: 'Eight-month documented window', path: 'period', min: 8, max: 8 },
      { id: 'ponzi-intake', label: 'Roughly $15 million taken in', path: 'totalInflow', min: 10_000_000, max: 20_000_000 },
    ],
  },
  {
    id: 'madoff',
    name: 'Bernard Madoff — 2008 liquidity run',
    kind: SCHEME_KINDS.INVESTMENT,
    mode: 'historical',
    immutable: true,
    historicalCaseId: 'madoff',
    description: 'A mature-fund replay of the final year, not a claim about when the fraud began.',
    seed: 2008,
    maxPeriods: 12,
    initialParticipants: 4_800,
    addressablePopulation: 65_000,
    initialReserve: 4_000_000_000,
    initialTotalInflow: 20_315_000_000,
    initialClaimedAccountValue: 64_800_000_000,
    growth: {
      recruitsPerParticipant: 0.006,
      recruitmentDecay: 0.94,
      churnRate: 0.01,
      churnSensitivity: 0.2,
      marketFriction: 1,
    },
    investment: {
      depositPerRecruit: 200_000,
      recurringDeposit: 0,
      promisedReturnRate: 0.008,
      withdrawalRate: 0.001,
      genuineRevenueRate: 0,
      operatorSkimRate: 0.01,
    },
    shocks: [
      { period: 9, label: 'The financial crisis increases redemption requests.', recruitmentMultiplier: 0.35, withdrawalMultiplier: 5, churnAdd: 0.04 },
      { period: 11, label: 'Withdrawal demands overwhelm the available cash.', recruitmentMultiplier: 0.05, withdrawalMultiplier: 12, churnAdd: 0.15 },
      { period: 12, label: 'The fraud is exposed in December 2008.', recruitmentMultiplier: 0, withdrawalMultiplier: 20, churnAdd: 0.35, freeze: true },
    ],
    benchmarks: [
      { id: 'madoff-window', label: 'Final-year replay', path: 'period', min: 12, max: 12 },
      { id: 'madoff-cash-scale', label: 'Cash claims remain in historical tens of billions', path: 'totalInflow', min: 20_000_000_000, max: 25_000_000_000 },
      { id: 'madoff-account-scale', label: 'Direct account scale remains bounded', path: 'totalJoined', min: 4_800, max: 10_000 },
    ],
  },
  {
    id: 'stanford',
    name: 'Allen Stanford — final-year run',
    kind: SCHEME_KINDS.INVESTMENT,
    mode: 'historical',
    immutable: true,
    historicalCaseId: 'stanford',
    description: 'A final-year liquidity replay anchored to the documented 20-year, $7 billion fraud.',
    seed: 2009,
    maxPeriods: 12,
    initialParticipants: 30_000,
    addressablePopulation: 50_000,
    initialReserve: 2_000_000_000,
    initialTotalInflow: 7_000_000_000,
    initialClaimedAccountValue: 7_000_000_000,
    growth: {
      recruitsPerParticipant: 0.004,
      recruitmentDecay: 0.92,
      churnRate: 0.012,
      churnSensitivity: 0.22,
      marketFriction: 1,
    },
    investment: {
      depositPerRecruit: 50_000,
      recurringDeposit: 0,
      promisedReturnRate: 0.006,
      withdrawalRate: 0.001,
      genuineRevenueRate: 0,
      operatorSkimRate: 0.015,
    },
    shocks: [
      { period: 8, label: 'New CD sales slow during the financial crisis.', recruitmentMultiplier: 0.3, withdrawalMultiplier: 3, churnAdd: 0.03 },
      { period: 11, label: 'Record redemptions expose the liquidity mismatch.', recruitmentMultiplier: 0.05, withdrawalMultiplier: 10, churnAdd: 0.12 },
      { period: 12, label: 'The SEC action freezes the operation in February 2009.', recruitmentMultiplier: 0, withdrawalMultiplier: 15, churnAdd: 0.3, freeze: true },
    ],
    benchmarks: [
      { id: 'stanford-window', label: 'Final-year replay', path: 'period', min: 12, max: 12 },
      { id: 'stanford-scale', label: 'Total cash remains near the documented $7 billion', path: 'totalInflow', min: 7_000_000_000, max: 8_000_000_000 },
      { id: 'stanford-participants', label: 'Participant count remains bounded', path: 'totalJoined', min: 30_000, max: 50_000 },
    ],
  },
  {
    id: 'zeek-rewards',
    name: 'Zeek Rewards, 2011–2012',
    kind: SCHEME_KINDS.RECRUITMENT,
    mode: 'historical',
    immutable: true,
    historicalCaseId: 'zeek-rewards',
    description: 'Hybrid pyramid/Ponzi replay calibrated to roughly $600 million and more than one million customers.',
    seed: 2012,
    maxPeriods: 20,
    initialParticipants: 1_000,
    addressablePopulation: 1_100_000,
    initialReserve: 1_000_000,
    growth: {
      recruitsPerParticipant: 0.58,
      recruitmentDecay: 0.992,
      churnRate: 0.025,
      churnSensitivity: 0.22,
      marketFriction: 1.5,
    },
    recruitment: {
      joinFee: 550,
      recurringPurchase: 30,
      retailSalesPerParticipant: 2,
      retailMargin: 0.2,
      refundRate: 0.05,
      productCostRate: 0.05,
      operatorSkimRate: 0.03,
      commissionRules: [
        { id: 'profit-pool', trigger: 'participant-purchase', depth: 1, rate: 0.5, minRank: 'bronze' },
        { id: 'recruitment-bonus', trigger: 'enrollment', depth: 1, rate: 0.12, minRank: 'bronze' },
      ],
      ranks: DEFAULT_RANKS,
    },
    shocks: [
      { period: 19, label: 'Cash payouts nearly match the month’s new inflows.', recruitmentMultiplier: 0.45, withdrawalMultiplier: 1, churnAdd: 0.1 },
      { period: 20, label: 'The SEC freezes the operation in August 2012.', recruitmentMultiplier: 0, withdrawalMultiplier: 1, churnAdd: 0.35, freeze: true },
    ],
    benchmarks: [
      { id: 'zeek-window', label: 'January 2011 to August 2012', path: 'period', min: 20, max: 20 },
      { id: 'zeek-people', label: 'Approximately one million customers', path: 'totalJoined', min: 700_000, max: 1_100_000 },
      { id: 'zeek-money', label: 'Approximately $600 million raised', path: 'totalInflow', min: 400_000_000, max: 800_000_000 },
    ],
  },
  {
    id: 'forsage',
    name: 'Forsage, 2020–2022',
    kind: SCHEME_KINDS.RECRUITMENT,
    mode: 'historical',
    immutable: true,
    historicalCaseId: 'forsage',
    description: 'A model of the recruitment mathematics alleged in the SEC’s 2022 charging release.',
    seed: 2022,
    maxPeriods: 31,
    initialParticipants: 5_000,
    addressablePopulation: 4_000_000,
    initialReserve: 500_000,
    growth: {
      recruitsPerParticipant: 0.35,
      recruitmentDecay: 0.997,
      churnRate: 0.035,
      churnSensitivity: 0.18,
      marketFriction: 1.55,
    },
    recruitment: {
      joinFee: 110,
      recurringPurchase: 0,
      retailSalesPerParticipant: 0,
      retailMargin: 0,
      refundRate: 0,
      productCostRate: 0.01,
      operatorSkimRate: 0.04,
      commissionRules: [
        { id: 'matrix-one', trigger: 'enrollment', depth: 1, rate: 0.5, minRank: 'bronze' },
        { id: 'matrix-two', trigger: 'enrollment', depth: 2, rate: 0.25, minRank: 'silver' },
      ],
      ranks: DEFAULT_RANKS,
    },
    shocks: [
      { period: 24, label: 'Regulatory warnings make recruitment harder.', recruitmentMultiplier: 0.72, withdrawalMultiplier: 1, churnAdd: 0.04 },
      { period: 31, label: 'The SEC files charges in August 2022; the release states allegations.', recruitmentMultiplier: 0, withdrawalMultiplier: 1, churnAdd: 0.25, freeze: true },
    ],
    benchmarks: [
      { id: 'forsage-window', label: 'Charging-release window', path: 'period', min: 31, max: 31 },
      { id: 'forsage-people', label: 'Millions of participants', path: 'totalJoined', min: 1_000_000, max: 4_000_000 },
      { id: 'forsage-money', label: 'More than $300 million raised', path: 'totalInflow', min: 250_000_000, max: 500_000_000 },
    ],
  },
  {
    id: 'burnlounge',
    name: 'BurnLounge, 2005–2007 operations',
    kind: SCHEME_KINDS.RECRUITMENT,
    mode: 'historical',
    immutable: true,
    historicalCaseId: 'burnlounge',
    description: 'A two-year operating-window replay of product packages and recruitment-driven rewards.',
    seed: 2007,
    maxPeriods: 24,
    initialParticipants: 1_000,
    addressablePopulation: 80_000,
    initialReserve: 250_000,
    growth: {
      recruitsPerParticipant: 0.39,
      recruitmentDecay: 0.99,
      churnRate: 0.055,
      churnSensitivity: 0.2,
      marketFriction: 1.45,
    },
    recruitment: {
      joinFee: 280,
      recurringPurchase: 15,
      retailSalesPerParticipant: 8,
      retailMargin: 0.3,
      refundRate: 0.05,
      productCostRate: 0.18,
      operatorSkimRate: 0.08,
      commissionRules: [
        { id: 'package-recruit', trigger: 'enrollment', depth: 1, rate: 0.34, minRank: 'bronze' },
        { id: 'team-package', trigger: 'enrollment', depth: 2, rate: 0.12, minRank: 'silver' },
      ],
      ranks: DEFAULT_RANKS,
    },
    shocks: [
      { period: 23, label: 'Regulatory scrutiny and participant losses slow recruitment.', recruitmentMultiplier: 0.4, withdrawalMultiplier: 1, churnAdd: 0.12 },
      { period: 24, label: 'The FTC files its complaint in 2007.', recruitmentMultiplier: 0, withdrawalMultiplier: 1, churnAdd: 0.3, freeze: true },
    ],
    benchmarks: [
      { id: 'burn-window', label: 'Two-year modeled operating window', path: 'period', min: 24, max: 24 },
      { id: 'burn-people', label: 'More than 56,000 consumers', path: 'totalJoined', min: 40_000, max: 75_000 },
    ],
  },
];

export function scenarioById(id) {
  return scenarios.find((scenario) => scenario.id === id) ?? scenarios[0];
}

export function scenariosForKind(kind) {
  return scenarios.filter((scenario) => scenario.kind === kind);
}

export function editableCopy(scenario) {
  return normalizeConfig({
    ...scenario,
    id: `${scenario.id}-what-if`,
    name: `${scenario.name} — what if`,
    immutable: false,
    mode: 'interactive',
    historicalCaseId: scenario.historicalCaseId,
    benchmarks: [],
  });
}

export const defaultScenarioForKind = {
  [SCHEME_KINDS.RECRUITMENT]: customRecruitment.id,
  [SCHEME_KINDS.INVESTMENT]: customInvestment.id,
};
